apiVersion: docker-machine.klusters.dev/v1alpha1
kind: Machine
metadata:
  name: rancher-vm-04
  namespace: demo
  annotations:
#    provider.kube-bind.appscode.com/cluster-id: 71a87546-b339-45ee-bca5-033d277faca2
    provider.kube-bind.appscode.com/cluster-id: 68d95713-cdbf-4fc1-96ed-ca2fc743ec7c
spec:
  driver:
    name: google
  authSecret:
    name: gcp-cred
    namespace: demo
  scriptRef:
    name: gcpscriptcreate
    namespace: demo
  parameters:
    "google-project": "example-testing"
    "google-zone": "testing"
    "google-machine-type": "n1-standard-2"
    "google-machine-image": "ubuntu-os-cloud/global/images/ubuntu-2204-jammy-sdfhrteh"