apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: connect
spec:
  version: {VERSION}
  homepage: https://appscode.com
  shortDescription: kubectl plugin for Kubernetes native Services by AppsCode
  description: |
    This plugin provides a list of commands to interact with KubeDB custom resources.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/bytebuilders/kube-bind/releases/download/{VERSION}/kubectl-connect-darwin-amd64.tar.gz
      sha256: {SHA256SUM_DARWIN_AMD64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-connect-darwin-amd64
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/bytebuilders/kube-bind/releases/download/{VERSION}/kubectl-connect-darwin-arm64.tar.gz
      sha256: {SHA256SUM_DARWIN_ARM64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-connect-darwin-arm64
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/bytebuilders/kube-bind/releases/download/{VERSION}/kubectl-connect-linux-amd64.tar.gz
      sha256: {SHA256SUM_LINUX_AMD64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-connect-linux-amd64
    - selector:
        matchLabels:
          os: linux
          arch: arm
      uri: https://github.com/bytebuilders/kube-bind/releases/download/{VERSION}/kubectl-connect-linux-arm.tar.gz
      sha256: {SHA256SUM_LINUX_ARM}
      files:
        - from: "*"
          to: "."
      bin: kubectl-connect-linux-arm
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/bytebuilders/kube-bind/releases/download/{VERSION}/kubectl-connect-linux-arm64.tar.gz
      sha256: {SHA256SUM_LINUX_ARM64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-connect-linux-arm64
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/bytebuilders/kube-bind/releases/download/{VERSION}/kubectl-connect-windows-amd64.zip
      sha256: {SHA256SUM_WINDOWS_AMD64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-connect-windows-amd64.exe
