apiVersion: kube-bind.io/v1alpha1
kind: APIServiceExportTemplate
metadata:
  name: mongodbs.kubedb.com
spec:
  permissionClaims:
    - target:
        apiVersion: "v1"
        kind: "Secret"
      labels:
        - exposed_by
      type: MatchSelector
      namespacePath: .metadata.namespace
      selector:
        matchLabels:
          "app.kubernetes.io/instance": "{.metadata.name}"
          "app.kubernetes.io/managed-by": kubedb.com
          "app.kubernetes.io/name": mongodbs.kubedb.com
      level: Owner
      verbs:
        provider:
          - "*"
        consumer:
          - get
          - list
          - watch
