apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeware
rules:
  - apiGroups:
      - "kubeware.dev"
    resources:
      - "apiserviceexportrequests"
    verbs: [ "create","delete","patch","update","get","list","watch" ]
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs: [ "get" ]
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs: [ "get", "watch", "list" ]
  - apiGroups:
      - "kubeware.dev"
    resources:
      - "clusterbindings"
    verbs: [ "get", "watch", "list" ]
  - apiGroups:
      - "kubeware.dev"
    resources:
      - "clusterbindings/status"
    verbs: [ "get","patch","update" ]
  - apiGroups:
      - "kubeware.dev"
    resources:
      - "apiserviceexports"
    verbs: [ "get", "watch", "list" ]
  - apiGroups:
      - "kubeware.dev"
    resources:
      - "apiserviceexports/status"
    verbs: [ "get","patch","update" ]
  - apiGroups:
      - "kubeware.dev"
    resources:
      - "apiservicenamespaces"
    verbs: [ "create","delete","patch","update","get","list","watch" ]
