/*
Copyright AppsCode Inc. and Contributors

Licensed under the AppsCode Community License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// APIServiceBindingListerExpansion allows custom methods to be added to
// APIServiceBindingLister.
type APIServiceBindingListerExpansion interface{}

// APIServiceExportListerExpansion allows custom methods to be added to
// APIServiceExportLister.
type APIServiceExportListerExpansion interface{}

// APIServiceExportNamespaceListerExpansion allows custom methods to be added to
// APIServiceExportNamespaceLister.
type APIServiceExportNamespaceListerExpansion interface{}

// APIServiceExportRequestListerExpansion allows custom methods to be added to
// APIServiceExportRequestLister.
type APIServiceExportRequestListerExpansion interface{}

// APIServiceExportRequestNamespaceListerExpansion allows custom methods to be added to
// APIServiceExportRequestNamespaceLister.
type APIServiceExportRequestNamespaceListerExpansion interface{}

// APIServiceNamespaceListerExpansion allows custom methods to be added to
// APIServiceNamespaceLister.
type APIServiceNamespaceListerExpansion interface{}

// APIServiceNamespaceNamespaceListerExpansion allows custom methods to be added to
// APIServiceNamespaceNamespaceLister.
type APIServiceNamespaceNamespaceListerExpansion interface{}

// ClusterBindingListerExpansion allows custom methods to be added to
// ClusterBindingLister.
type ClusterBindingListerExpansion interface{}

// ClusterBindingNamespaceListerExpansion allows custom methods to be added to
// ClusterBindingNamespaceLister.
type ClusterBindingNamespaceListerExpansion interface{}
