name: Release

on:
  pull_request:
    paths:
    - .github/workflows/goreleaser.yaml
    - .goreleaser.yaml
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-tags: true
        fetch-depth: 0
    - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version: v1.26.2
    - name: Delete non-semver tags
      run: 'git tag -d $(git tag -l | grep -v "^v")'
    - name: Set LDFLAGS
      run: echo LDFLAGS="$(make ldflags)" >> $GITHUB_ENV
    - name: Run GoReleaser on tag
      if: github.event_name != 'pull_request'
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: release --timeout 60m
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KREW_GITHUB_TOKEN: ${{ secrets.KREW_GITHUB_TOKEN }}
    - name: Run GoReleaser on pull request
      if: github.event_name == 'pull_request'
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: release --timeout 60m --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KREW_GITHUB_TOKEN: ${{ secrets.KREW_GITHUB_TOKEN }}
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ always() }}
      with:
        name: binaries
        path: dist/*.tar.gz
